routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',                       'WelcomeController@index')->name('welcome');

// ================================= RESOURCE ROUTES
Route::resource('calls',  'CallController');
Route::resource('users',  'UserController');
Route::resource('clients', 'ClientController');

// ===================================== IMPORT ROUTE
Route::post('/calls/import',           'CallController@importCall')->name('calls.import');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['full_name', 'client_type'];

    public function calls()
    {
        return $this->hasMany(Call::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ClientRequest;
use App\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->paginate(10);

        return view('pages.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientRequest $request)
    {
        $dataToStore = $request->validated();

        $success = Client::create($dataToStore);

        if($success) {
            
            return redirect()->route('clients.index')->withSuccess('Success: Client was created successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('pages.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, Client $client)
    {
        $dataToStore = $request->validated();

        $success = $client->update($dataToStore);

        if($success) {

            return redirect()->route('clients.index')->withSuccess('Success: Client was updated successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //If this client have calls under it, dont allow to be deleted...
        if(count($client->calls)) {
            
            return redirect()->back()
                ->withErrors(['warning' => "Warning: Can't delete client, has calls under it!"]);
        }

        if($client->delete()) {

            return redirect()->back()->withSuccess('Success: Client was deleted successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
    }
}

resources/views/pages/clients/create.blade.php
@extends('layouts.app')
    
@section('content')

@include('inc.errors.error')
@include('inc.successes.success')

<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card">
            <div class="card-header card-header-primary">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <h4 class="card-title">Create</h4>
                        <p class="card-category">Complete all fields</p>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('clients.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Clent full name</label>
                                <input type="text" class="form-control" name="full_name" required value="{{ old('full_name') }}">
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn">Create</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</div>

@endsection

resources/views/pages/clients/edit.blade.php
@extends('layouts.app')
    
@section('content')

@include('inc.errors.error')
@include('inc.successes.success')

<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card">
            <div class="card-header card-header-primary">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <h4 class="card-title">Edit</h4>
                        <p class="card-category">Complete all fields</p>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('clients.update', $client->id) }}">
                    @csrf
                    @method('PUT')
                    
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Clent full name</label>
                                <input type="text" class="form-control" name="full_name" required value="{{ $client->full_name }}">
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn">Edit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</div>

@endsection

resources/views/pages/clients/index.blade.php
@extends('layouts.app')

@section('content')

    @include('inc.errors.error')
    @include('inc.successes.success')

    <div class="row">
        <div class="card card-nav-tabs card-plain">
            
            <div class="card-header card-header-primary">
                <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <ul class="nav nav-tabs pull-left">
                            <li class="nav-item">
                                <a href="{{ route('clients.create') }}" class="btn btn-sm btn-secondary text-primary">Create</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <div class="tab-content text-center">
                    <div class="tab-pane active" id="clients">
                        <table class="table">

                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Client</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>

                                @forelse ($clients as $count => $client)
                                    
                                    <tr>
                                        <td>{{ $count + 1 }}</td>
                                        <td>{{ $client->full_name }}</td>
                                        
                                        <td>
                                            <a href="{{ route('clients.edit', $client->id) }}" rel="tooltip" class="btn btn-warning btn-link btn-sm p-0" title="Edit">
                                                <i class="material-icons">edit</i>
                                            </a>
                                            <button type="button" rel="tooltip" class="btn btn-danger btn-link btn-sm p-0" title="Delete" 
                                                    data-toggle="modal" data-target="#deleteModalClient{{$client->id}}">
                                                <i class="material-icons">close</i>
                                            </button>
                                        </td>
                                    </tr>

                                    {{-- DELETE MODAL --}}
                                    @include('inc.modals.deleteModal', [
                                        'route' => route('clients.destroy', $client->id),
                                        'deleteModalId' => 'deleteModalClient'.$client->id,
                                        'deleteModalLabel' => 'deleteModalLabelClient',
                                        'item' => 'Client'
                                    ])

                                @empty
                                    <h4>No records!</h4>
                                @endforelse

                            </tbody>

                        </table>

                        <hr>
                        <div class="d-flex justify-content-between">
                            <span>{{ $clients->links() }}</span>
                            <span> <strong>Total:</strong> {{ $clients->total() }}</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection