routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',                       'WelcomeController@index')->name('welcome');

// ================================= RESOURCE ROUTES
Route::resource('calls',  'CallController');
Route::resource('users',  'UserController');
Route::resource('clients', 'ClientController');

// ===================================== IMPORT ROUTE
Route::post('/calls/import',           'CallController@importCall')->name('calls.import');

app/Call.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    protected $fillable = ['user_id', 'client_id', 'date', 'duration', 'type_of_call', 'external_call_score'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id', 'id');
    }


}

app/Http/Controllers/CallController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CallRequest;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\CallsImport;
use App\Call;
use App\User;
use App\Client;
use Illuminate\Support\Facades\Storage;

class CallController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $calls = Call::with('user', 'client')
                    ->latest()
                    ->paginate(10);

        return view('pages.calls.index', compact('calls'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $clients = Client::all();
        $typeOfCall = ['Incoming', 'Outgoing'];

        return view('pages.calls.create', compact('users','clients','typeOfCall'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CallRequest $request)
    {
        $dataToStore = $request->validated();

        $success = Call::create($dataToStore);

        if($success) {

            return redirect()->route('calls.index')->withSuccess('Success: Call was created successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Call $call)
    {
        $users = User::all();
        $clients = Client::all();
        $typeOfCall = ['Incoming', 'Outgoing'];

        return view('pages.calls.edit', compact('call', 'users','clients','typeOfCall'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CallRequest $request, Call $call)
    {
        $dataToUpdate = $request->validated();

        $success = $call->update($dataToUpdate);

        if($success) {

            return redirect()->route('calls.index')->withSuccess('Success: Call was updated successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Call $call)
    {
        $success = $call->delete();
        
        if($success) {

            return redirect()->back()->withSuccess('Success: Call was deleted successfully!');
        }

        return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
    }

    public function importCall(Request $request)
    {
        //Valdate data
        $dataToStore = $request->validate([
            'file' => 'required|mimes:csv,txt',
        ]);

        // Store file data localy
        $storedCallsPath = $request->file('file')->store('imported_calls');

        try {

            // Take stored file data, and put through CallsImport class, so that we can save it to the database
            Excel::import(new CallsImport, $storedCallsPath);

            // Delete stored file data, if saving to databas was successfull...
            Storage::deleteDirectory('imported_calls');

            return redirect()->back()->withSuccess('Success: file was uploaded successfully!');

        } catch (\Exception $e) {
            
            return redirect()->back()->withErrors('error', 'Ups! Something went wrong, please try again!');
        }

    }
}

resources/views/pages/calls/create.blade.php
@extends('layouts.app')
    

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    
    <style>
        .actions {
            display: fixed;
        }
        .hidden {
            display: none;
        }
        .filter-option-inner-inner, .dropdown-toggle:after{
            color: #999999 !important;
        }

        .dropdown-menu li a:hover{
            background-color: #4db6ac !important;
        }

        .btn-link {
            background-color: transparent !important;
        }

        .btn-active {
            background: #999999!important;
            color: white!important;
        }
    </style>

@endsection

@section('content')

@include('inc.errors.error')
@include('inc.successes.success')

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card">
            <div class="card-header card-header-primary">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <h4 class="card-title">Create Call</h4>
                        <p class="card-category">Complete all fields</p>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('calls.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Date</label>
                                <input type="text" class="form-control datetimepicker" name="date" required value="{{ old('date') }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Duration</label>
                                <input type="text" class="form-control" name="duration" required value="{{ old('duration') }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">External call score</label>
                                <input type="text" class="form-control" name="external_call_score" required value="{{ old('external_call_score') }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select user</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="selectUser" name="user_id" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select client</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="selectClient" name="client_id" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($clients as $client)
                                        <option value="{{ $client->id }}">{{ $client->full_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select Type of call</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="type_of_call" name="type_of_call" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($typeOfCall as $type)
                                        <option value="{{ $type }}">{{ $type }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/pages/calls/edit.blade.php
@extends('layouts.app')
    

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    
    <style>
        .actions {
            display: fixed;
        }
        .hidden {
            display: none;
        }
        .filter-option-inner-inner, .dropdown-toggle:after{
            color: #999999 !important;
        }

        .dropdown-menu li a:hover{
            background-color:#4db6ac !important;
        }

        .btn-link {
            background-color: transparent !important;
        }

        .btn-active {
            background: #999999!important;
            color: white!important;
        }
    </style>

@endsection

@section('content')

@include('inc.errors.error')
@include('inc.successes.success')

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card">
            <div class="card-header card-header-primary">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <h4 class="card-title">Edit Call</h4>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('calls.update', $call->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Date</label>
                                <input type="date" class="form-control" name="date" required value="{{ $call->date }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">Duration</label>
                                <input type="text" class="form-control" name="duration" required value="{{ $call->duration }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-static">External call score</label>
                                <input type="text" class="form-control" name="external_call_score" required value="{{ $call->external_call_score }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select user</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="selectUser" name="user_id" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}"  {{ $user->id == $call->user_id ? 'selected' : '' }}>{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select client</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="selectClient" name="client_id" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($clients as $client)
                                        <option value="{{ $client->id }}" {{ $client->id == $call->client_id ? 'selected' : '' }}>{{ $client->full_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="selectUser">Select Type of call</label>
                                <select class="form-control selectpicker" data-style="btn btn-link" id="type_of_call" name="type_of_call" required>
                                    <option value="" selected disabled>Please select</option>
                                    @foreach($typeOfCall as $type)
                                        <option value="{{ $type }}" {{ $type == $call->type_of_call ? 'selected' : '' }}>{{ $type }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/pages/calls/index.blade.php
@extends('layouts.app')

@section('content')

    @include('inc.errors.error')
    @include('inc.successes.success')

    <div class="row">
        <div class="card card-nav-tabs card-plain">
            
            <div class="card-header card-header-primary">
                <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                        <ul class="nav nav-tabs pull-left">
                            <li class="nav-item">
                               <button type="button" class="btn btn-sm btn-secondary text-primary" data-toggle="modal" data-target="#importCallsModal">Upload CSV</button>
                                <a href="{{ route('calls.create') }}" class="btn btn-sm btn-secondary text-primary">Create</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <div class="tab-content text-center">
                    <div class="tab-pane active" id="calls">
                        <table class="table">

                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>User</th>
                                    <th>Client</th>
                                    <th>Client Type</th>
                                    <th>Date</th>
                                    <th>Duration</th>
                                    <th>Type Of Call</th>
                                    <th>External Call Score</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>

                                @forelse ($calls as $count => $call)
                                    
                                    <tr>
                                        <td>{{ $count + 1 }}</td>
                                        <td>{{ $call->user->name }}</td>
                                        <td>{{ $call->client->full_name }}</td>
                                        <td>{{ $call->client->client_type }}</td>
                                        <td>{{ $call->date }}</td>
                                        <td>{{ $call->duration }}</td>
                                        <td>{{ $call->type_of_call }}</td>
                                        <td>{{ $call->external_call_score }}</td>
                                        <td>
                                            <a href="{{ route('calls.edit', $call->id) }}" rel="tooltip" class="btn btn-warning btn-link btn-sm p-0" title="Edit">
                                                <i class="material-icons">edit</i>
                                            </a>
                                            <button type="button" rel="tooltip" class="btn btn-danger btn-link btn-sm p-0" title="Delete" 
                                                    data-toggle="modal" data-target="#deleteModalCall{{$call->id}}">
                                                <i class="material-icons">close</i>
                                            </button>
                                        </td>
                                    </tr>

                                    {{-- DELETE MODAL --}}
                                    @include('inc.modals.deleteModal', [
                                        'route' => route('calls.destroy', $call->id),
                                        'deleteModalId' => 'deleteModalCall'.$call->id,
                                        'deleteModalLabel' => 'deleteModalLabelCall',
                                        'item' => 'Call'
                                    ])

                                @empty
                                    <h4>No records!</h4>
                                @endforelse

                            </tbody>

                        </table>

                        <hr>
                        <div class="d-flex justify-content-between">
                            <span>{{ $calls->links() }}</span>
                            <span> <strong>Total:</strong> {{ $calls->total() }}</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- CSV UPLOAD MODAL --}}
    @include('inc.modals.uploadCsvModal')
    
@endsection